# Generated by Django 4.0.3 on 2022-04-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='кличка животного')),
                ('age', models.PositiveIntegerField(verbose_name='возраст животного')),
                ('date_from', models.DateField(verbose_name='дата прибытия в приют')),
                ('weight', models.PositiveIntegerField(verbose_name='вес животного')),
                ('growth', models.PositiveIntegerField(verbose_name='рост животного')),
                ('special_signs', models.CharField(max_length=200, verbose_name='особые приметы животного')),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
